FileVersion = 1
Projects = {
  SDL3 = {Path = "../SDL3-Beef"},
  SDL3_image = {Path = "../SDL3_image-Beef"},
  Engine = {Path = "Engine"},
  Game = {Path = "Game"}
}

[Workspace]
StartupProject = "Game"
