FileVersion = 1
Projects = {
  SDL3 = {Path = "../SDL3-Beef"},
  SDL3_image = {Path = "../SDL3_image-Beef"},
  engine = {Path = "engine"},
  game = {Path = "game"}
}

[Workspace]
StartupProject = "game"
